
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:3.4.0
    container_name: localstack_container
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"  # LocalStack Gateway
    volumes:
      - localstack_data:/var/lib/localstack
      - ./init/aws/init-localstack.sh:/etc/localstack/init/ready.d/init.sh

volumes:
    postgres_data:
    localstack_data: